# [N]:local - For local development, connecting to local Docker containers, and overriding the AWS clients to point to localhost.
spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: spring-boot-application
            clientSecret: 27b07baf-53ba-42c6-b11f-6384769cada3
            scope: openid
        provider:
          cognito:
            issuerUri: http://localhost:8888/auth/realms/stratospheric
  cloud:
    aws:
      # [N]:local - We have to override our Java AWS SDK clients to connect to LocalStack. With Spring Cloud AWS, we can conveniently override the endpoint URLs and regions for all AWS SDK clients. When it comes to configuring the AWS credentials for the local setup, LocalStack bypasses any AWS client authentication hence, we hardcode the AWS credentials with any value.
      credentials:
        secret-key: foo
        access-key: bar
      endpoint: http://localhost:4566
      region:
        static: us-east-1

custom:
  use-cognito-as-identity-provider: false
