server:
  forward-headers-strategy: framework

spring:
  application:
    name: todo-app
  cloud:
    aws:
      region:
        # [N] To configure the AWS region, we use the Spring Cloud AWS static region configuration.
        static: us-east-1

custom:
  invitation-codes: DUKE, STRATOSPHERIC
