server:
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: todo-app
  cloud:
    aws:
      region:
        # [N] To configure the AWS region, we use the Spring Cloud AWS static region configuration.
        static: us-east-1
      sns:
        enabled: false

management:
  health:
    jms:
      enabled: false # don't verify the health of the JMS broker
  cloudwatch:
    metrics:
      export:
        enabled: true
        namespace: stratospheric
        step: 1m
  metrics:
    tags:
      environment: ${ENVIRONMENT_NAME}

# configuration of error-handling-spring-boot-starter (https://wimdeblauwe.github.io/error-handling-spring-boot-starter/)
error:
  handling:
    exception-logging: WITH_STACKTRACE

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database

  # [N]:sqs]:share - The queue used to prompt collaboration requests
  sharing-queue: stratospheric-todo-sharing

  # [N]:share - The URL of the endpoint that a prospect collaborator will use to confirm a collaboration request.
  external-url: https://app.hjolystratos.net

  # [N]:local]:share - In local configuration, as collaboration requests are sent to fictitious users, we auto-confirm collaborations.
  auto-confirm-collaborations: false

  # [N]:share - The sender of the email confirming the collaboration.
  confirm-email-from-address: noreply@hjolystratos.net

  environment: ${ENVIRONMENT_NAME}
