# [N] For running the application on AWS in production mode.
spring:
  security:
    oauth2:
      client:
        registration:
          # [N]:security]:cognito - Specifies the OpenID Discovery endpoint of Cognito, our identity provider. The ${} placeholders will be replaced with environment variables that we specify when deploying our Todo application with ECS (see dev.stratospheric.todoapp.cdk.ServiceApp.environmentVariables). The ${} is a typical usage of SpEL - Spring’s powerful expression language (see https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi2jayZ5e3_AhW3kIkEHXE-B2wQFnoECA4QAQ&url=https%3A%2F%2Fwww.baeldung.com%2Fspring-expression-language&usg=AOvVaw3D9u2acVyGWEIEkSYtWAmG&opi=89978449)).
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: stratospheric-users-client
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}
  activemq:
    broker-url: ${WEB_SOCKET_RELAY_ENDPOINT}
    user: ${WEB_SOCKET_RELAY_USERNAME}
    password: ${WEB_SOCKET_RELAY_PASSWORD}

management:
  cloudwatch:
    metrics:
      export:
        enabled: false # disabled to save some $$$ on our monthly AWS bill

custom:
  sharing-queue: ${TODO_SHARING_QUEUE_NAME}
  web-socket-relay-use-ssl: true
  provide-test-todo-controller: false
  use-cognito-as-identity-provider: true
