package dev.stratospheric.todoapp.tracing;

import org.springframework.context.ApplicationEvent;

/**
 * [N]:spring-evnt - A Spring {@code ApplicationEvent} used to keep the code for tracing users separate from our actual business logic and decouple the event of a user visiting a path from storing the data generated by that event.<p/>
 * {@link ApplicationEvent}s allow for the exchange of information between loosely coupled components using the familiar publish-subscribe pattern.
 * @See <a href="https://docs.spring.io/spring-integration/docs/current/reference/html/event.html">Spring application events</a>.
 */
public class TracingEvent extends ApplicationEvent {

  private final String uri;
  private final String username;

  /**
   *  
   * @param source the object on which the event initially occurred or with which the event is associated
   * @param uri
   * @param username
   */
  public TracingEvent(Object source, String uri, String username) {
    super(source);

    this.uri = uri;
    this.username = username;
  }

  public String getUri() {
    return uri;
  }

  public String getUsername() {
    return username;
  }
}
